{"name": "Вставить в поле ввода очень длинное значение (373 символа)", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'int'", "trace": "@allure.epic(\"Тестирование UI\")\n    @allure.feature(\"Негативные проверки\")\n    @allure.title(\"Вставить в поле ввода очень длинное значение (373 символа)\")\n    @allure.description(\"В результате теста проверяется что при вводе\\\n        в поле ввода слишком большого значения, в поле ввода остается\\\n            только 150 символов\")\n    def test_negitive_very_long_value_in_input():\n        with allure.step(\"Создать объект класса MainsPage\"):\n            main_page = MainsPage()\n        with allure.step(\"Зайти на главную страницу\"):\n            main_page.go_to_main_page()\n        with allure.step(\"Ввести в поле ввода очень длинное значение (373)\"):\n            main_page.send_keys_input(long_name_373)\n            allure.attach(long_name_373, \"Введенное значение\")\n            WebDriverWait(main_page.browser, 10, 0.1).until(\n                EC.visibility_of_element_located(\n                    (By.CSS_SELECTOR, \".result-item__mark\")))\n        with allure.step(\"Получить значение подсказки из выпадающего списка\"):\n            elem = main_page.browser.find_element(\n                By.CSS_SELECTOR, \".result-item__mark\").text\n            len_elem = len(elem)\n>           allure.attach(len(elem), \"Длинна значения\")\n\ntests\\test_ui.py:172: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py:200: in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_hooks.py:513: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_pytest\\listener.py:252: in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\reporter.py:165: in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_hooks.py:513: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_commons.logger.AllureFileLogger object at 0x000001F7250E3620>, body = 150\nfile_name = '55858dc1-8558-4455-a9c7-2972254e49f8-attachment.attach'\n\n    @hookimpl\n    def report_attached_data(self, body, file_name):\n        destination = self._report_dir / file_name\n        with open(destination, 'wb') as attached_file:\n            if isinstance(body, str):\n                attached_file.write(body.encode('utf-8'))\n            else:\n>               attached_file.write(body)\nE               TypeError: a bytes-like object is required, not 'int'\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\logger.py:48: TypeError"}, "description": "В результате теста проверяется что при вводе    в поле ввода слишком большого значения, в поле ввода остается        только 150 символов", "steps": [{"name": "Создать объект класса MainsPage", "status": "passed", "start": 1738056356113, "stop": 1738056358940}, {"name": "Зайти на главную страницу", "status": "passed", "attachments": [{"name": "Используемый URL", "source": "279d2ad5-005e-48d2-b5ba-a0541f87064c-attachment.attach"}], "start": 1738056358941, "stop": 1738056400474}, {"name": "Ввести в поле ввода очень длинное значение (373)", "status": "passed", "steps": [{"name": "Очистить поле ввода", "status": "passed", "start": 1738056400474, "stop": 1738056400536}, {"name": "Ввести в поле ввода значение", "status": "passed", "attachments": [{"name": "Введенное значение", "source": "8998c79b-5f90-4029-a388-e600db02a336-attachment.attach"}], "start": 1738056400536, "stop": 1738056401324}, {"name": "Подождать прогрузки необходимых элементов", "status": "passed", "start": 1738056401324, "stop": 1738056411402}], "attachments": [{"name": "Введенное значение", "source": "6f8434b6-3c50-4b6a-8618-ec834ddb2b52-attachment.attach"}], "start": 1738056400474, "stop": 1738056411426}, {"name": "Получить значение подсказки из выпадающего списка", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'int'\n", "trace": "  File \"c:\\Users\\DEXP\\Desktop\\Diploma work on automation\\Diploma-work-on-automation\\tests\\test_ui.py\", line 172, in test_negitive_very_long_value_in_input\n    allure.attach(len(elem), \"Длинна значения\")\n    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_pytest\\listener.py\", line 252, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DEXP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n    ~~~~~~~~~~~~~~~~~~~^^^^^^\n"}, "attachments": [{"name": "Длинна значения", "source": "55858dc1-8558-4455-a9c7-2972254e49f8-attachment.attach"}], "start": 1738056411426, "stop": 1738056411448}], "attachments": [{"name": "stdout", "source": "570a1f5f-c0fc-4e00-a6c8-48f798e6c52c-attachment.txt", "type": "text/plain"}], "start": 1738056356113, "stop": 1738056411452, "uuid": "71bdcd6f-689d-47ba-bf51-70e703e49bd3", "historyId": "2cb02fcb01faebc9e5ecdb8da79942f6", "testCaseId": "2cb02fcb01faebc9e5ecdb8da79942f6", "fullName": "tests.test_ui#test_negitive_very_long_value_in_input", "labels": [{"name": "feature", "value": "Негативные проверки"}, {"name": "epic", "value": "Тестирование UI"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_ui"}, {"name": "host", "value": "DESKTOP-Q56RGJ9"}, {"name": "thread", "value": "8944-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_ui"}]}